package com.android.gallery3d.filtershow.filters;

import com.android.gallery3d.filtershow.ui.Spline;

/**
 * TODO: Insert description here. (generated by hoford)
 */
public class FilterCurvesRepresentation extends FilterRepresentation {
    private Spline[] mSplines = new Spline[4];
    public FilterCurvesRepresentation() {
        super("Curves");
        for (int i = 0; i < mSplines.length; i++) {
            mSplines[i] = new Spline();
            mSplines[i].reset();
        }
    }

    public void reset() {
        Spline spline = new Spline();

        spline.addPoint(0.0f, 1.0f);
        spline.addPoint(1.0f, 0.0f);

        for (int i = 0; i < 4; i++) {
            mSplines[i] = new Spline(spline);
        }
    }

    public void setSpline(int splineIndex, Spline s) {
        mSplines[splineIndex] = s;
    }
    public Spline getSpline(int splineIndex) {
        return mSplines[splineIndex];
    }
}
