package com.android.gallery3d.filtershow.imageshow;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Rect;

/**
 * TODO: Insert description here. (generated by hoford)
 */
public class ImageWithIcon extends ImageSmallFilter {
    /**
     * @param context
     */
    public ImageWithIcon(Context context) {
        super(context);
        // TODO(hoford): Auto-generated constructor stub
    }

    private Bitmap bitmap;

    public void setIcon(Bitmap bitmap){
        this.bitmap = bitmap;
    }

    @Override
    public void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        if (bitmap != null) {
            Rect d = new Rect(0, mMargin, getWidth() - mMargin, getWidth());
            drawImage(canvas, bitmap, d);
        }
    }
}
